-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 06, 2026 at 07:35 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `psikotest`
--

-- --------------------------------------------------------

--
-- Table structure for table `soaltpa`
--

CREATE TABLE `soaltpa` (
  `id_soal` int(11) NOT NULL,
  `soal` varchar(999) DEFAULT NULL,
  `jawaban` varchar(2) DEFAULT NULL,
  `id_kategori` varchar(11) DEFAULT NULL,
  `A` varchar(999) NOT NULL,
  `B` varchar(999) NOT NULL,
  `C` varchar(999) NOT NULL,
  `D` varchar(999) NOT NULL,
  `E` varchar(999) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `soaltpa`
--

INSERT INTO `soaltpa` (`id_soal`, `soal`, `jawaban`, `id_kategori`, `A`, `B`, `C`, `D`, `E`) VALUES
(1, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Perbedaan utama antara <strong>BPUPKI dan PPKI</strong> dalam proses kemerdekaan adalah&hellip;</span></span></p>', 'B', '1', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">BPUPKI membentuk UUD, PPKI membubarkannya</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">BPUPKI merumuskan, PPKI mengesahkan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">BPUPKI mengesahkan, PPKI merumuskan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Keduanya memiliki tugas yang sama</span></span></p>', ''),
(2, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Makna sila ke-3 Pancasila dalam kehidupan berbangsa adalah&hellip;</span></span></p>', 'B', '1', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Kebebasan individu</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Persatuan dalam keberagaman</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Keadilan ekonomi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Demokrasi langsung</span></span></p>', ''),
(3, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pasal dalam UUD 1945 yang mengatur tentang <strong>hak asasi manusia</strong> terdapat pada&hellip;</span></span></p>', 'B', '1', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pasal 27</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pasal 28A&ndash;28J</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pasal 30</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pasal 33</span></span></p>', ''),
(4, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Dalam sistem pemerintahan Indonesia, kekuasaan legislatif dijalankan oleh&hellip;</span></span></p>', 'C', '1', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Presiden</span></span></p>', '<p>Mahkamah Agung</p>', '<p>DPR</p>', '<p>MPR saja</p>', ''),
(5, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Perubahan UUD 1945 dilakukan pada masa&hellip;</span></span></p>', 'C', '1', '<p>Orde lama</p>', '<p>Orde baru</p>', '<p>Reformasi</p>', '<p>Demokrasi Terpimpin</p>', ''),
(6, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Nilai utama dari semboyan <strong>Bhinneka Tunggal Ika</strong> adalah&hellip;</span></span></p>', 'C', '1', '<p>Keseragaman Budaya</p>', '<p>Dominasi Mayoritas</p>', '<p>Toleransi dalam Perbedaan</p>', '<p>Persaingan antar Daerah</p>', ''),
(7, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Tujuan negara Indonesia tercantum dalam&hellip;</span></span></p>', 'B', '1', '<p>Batang tubuh UUD</p>', '<p>Pembukaan UUD 1945 alinea ke - 4&nbsp;</p>', '<p>Pasal 1 UUD</p>', '<p>Penjelasan UUD</p>', ''),
(8, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Kedaulatan rakyat menurut UUD 1945 berada di tangan&hellip;</span></span></p>', 'C', '1', '<p>Presiden</p>', '<p>DPR</p>', '<p>Rakyat</p>', '<p>MPR saja</p>', ''),
(9, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Contoh implementasi sila ke-5 dalam kehidupan sehari-hari adalah&hellip;</span></span></p>', 'C', '1', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Beribadah sesuai agama</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Gotong royong</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membantu sesama secara adil</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menghormati perbedaan</span></span></p>', ''),
(10, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Negara Indonesia disebut sebagai negara hukum, artinya&hellip;</span></span></p>', 'B', '1', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pemerintah bebas bertindak</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Hukum berada di atas segalanya</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Rakyat bebas tanpa aturan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Presiden sebagai hukum tertinggi</span></span></p>', ''),
(26, '<p><strong><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Deret Angka 2, 6, 7, 21, 22, 66, &hellip;</span></span></strong></p>', 'A', '2', '<p>67</p>', '<p>68</p>', '<p>69</p>', '<p>70</p>', ''),
(27, '<p><strong><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Dokter : Pasien = Guru : &hellip;</span></span></strong></p>', 'B', '2', '<p>Sekolah</p>', '<p>Murid</p>', '<p>Guru</p>', '<p>Kelas</p>', ''),
(28, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Semua A adalah B, sebagian B adalah C. Maka&hellip;</span></span></p>', 'C', '2', '<p>Semua A adalah C</p>', '<p>Sebagian A adalah C</p>', '<p>Tidak dapat disimpulkan</p>', '<p>Semua C adalah A</p>', ''),
(29, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Jika 5x + 3 = 28, maka x = &hellip;</span></span></p>', 'A', '2', '<p>4</p>', '<p>5</p>', '<p>6</p>', '<p>7</p>', ''),
(30, '<p><strong><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">A, C, F, J, O, &hellip;</span></span></strong></p>', 'B', '2', '<p>T</p>', '<p>U</p>', '<p>V</p>', '<p>W</p>', ''),
(31, '<p><strong><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">3 : 9 = 4 : &hellip;</span></span></strong></p>', 'A', '2', '<p>12</p>', '<p>13</p>', '<p>14</p>', '<p>15</p>', ''),
(32, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Semua bunga indah. Mawar adalah bunga. Maka&hellip;</span></span></p>', 'B', '2', '<p>Mawar tidak Indah</p>', '<p>Mawar Indah</p>', '<p>Tidak pasti</p>', '<p>Semua Indah Mawar</p>', ''),
(33, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Jika 12 orang menyelesaikan pekerjaan dalam 6 hari, maka 6 orang butuh&hellip;</span></span></p>', 'B', '2', '<p>10 hari</p>', '<p>12 hari</p>', '<p>11 hari</p>', '<p>13 hari</p>', ''),
(34, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">&ldquo;Efisien&rdquo; paling dekat artinya&hellip;</span></span></p>', 'B', '2', '<p>Cepat</p>', '<p>Tepat Guna</p>', '<p>Hemat</p>', '<p>Mudah</p>', ''),
(35, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Jika semua X adalah Y, dan semua Y adalah Z&hellip;</span></span></p>', 'A', '2', '<p>Semua X adalah Z</p>', '<p>Sebagian X adalah Z</p>', '<p>Tidak pasti</p>', '<p>Semua Z adalah X</p>', ''),
(51, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga lansia kesulitan layanan digital. Anda&hellip;</span></span></p>', 'A', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mendampingi sampai benar-benar paham dan bisa mandiri</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mendampingi hingga proses selesai saja</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke petugas lain</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyuruh kembali dengan keluarga</span></span></p>', ''),
(52, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Rekan kerja sering terlambat menyelesaikan tugas. Anda&hellip;</span></span></p>', 'A', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membantu sambil membangun kesadaran tanggung jawabnya</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membantu tanpa menyinggung tanggung jawabnya</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengingatkan saja</span></span></p>', '<p>Membiarkan</p>', ''),
(53, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Tugas mendadak di luar jam kerja. Anda&hellip;</span></span></p>', 'C', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menolak dengan alasan pribadi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membantu jika sangat mendesak saja</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membantu penuh sebagai tanggung jawab</span></span></p>', '<p>Mengabaikan</p>', ''),
(54, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga marah karena pelayanan lambat. Anda&hellip;</span></span></p>', 'A', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menenangkan dan memberikan solusi konkret</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menenangkan tanpa solusi jelas</span></span></p>', '<p>Membela diri</p>', '<p>Menghindari</p>', ''),
(55, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menemukan kesalahan kecil dalam laporan tim. Anda&hellip;</span></span></p>', 'A', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memperbaiki dan memberi penjelasan ke tim</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memperbaiki tanpa penjelasan detail</span></span></p>', '<p>Mengingatkan saja</p>', '<p>Membiarkan</p>', ''),
(56, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Lingkungan kerja tidak kondusif. Anda&hellip;</span></span></p>', 'A', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menginisiasi perbaikan suasana kerja</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjaga sikap positif secara pribadi saja</span></span></p>', '<p>Menghindari</p>', '<p>Membiarkan</p>', ''),
(57, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Bekerja dengan orang yang tidak cocok. Anda&hellip;</span></span></p>', 'A', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Tetap profesional dan membangun kerja sama<strong><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\"> </span></span></strong>aktif</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Tetap profesional tanpa interaksi lebih</span></span></p>', '<p>Menghindari</p>', '<p>Pasif</p>', ''),
(58, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Perubahan sistem kerja mendadak. Anda&hellip;</span></span></p>', 'B', '3', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Belajar untuk diri sendiri saja</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Cepat belajar dan membantu adaptasi tim</span></span></p>', '<p>Mengeluh</p>', '<p>Menolak</p>', ''),
(59, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga minta prioritas tanpa alasan. Anda&hellip;</span></span></p>', 'D', '3', '<p>Mengabaikan</p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menolak dengan penjelasan singkat saja</span></span></p>', '<p>Mengabulkan</p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menolak dengan penjelasan aturan dan empati</span></span></p>', ''),
(60, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Diberi tanggung jawab besar. Anda&hellip;</span></span></p>', 'B', '3', '<p>Ragu-ragu</p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengerjakan dengan penuh komitmen dan perencanaan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengerjakan dengan komitmen tanpa perencanaan matang</span></span></p>', '<p>Menolak</p>', ''),
(76, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Dana desa digunakan tanpa musyawarah. Tindakan terbaik&hellip;</span></span></p>', 'D', '4', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Tetap dilanjutkan agar program berjalan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Melaporkan langsung ke aparat hukum</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengikuti keputusan kepala desa</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menghentikan sementara dan lakukan musyawarah</span></span></p>', ''),
(77, '<p>Peraturan desa dibuat tanpa melibatkan BPD. Anda&hellip;</p>', 'C', '4', '<p>Tetap menjalankan sambil mempertimbangkan perbaikan di tahap berikutnya</p>', '<p>Mengkoordinasikan dengan pihak terkait untuk evaluasi dan penyesuaian prosedur</p>', '<p>Menginisiasi revisi peraturan dengan melibatkan BPD sesuai ketentuan yang berlaku</p>', '<p>Meninjau ulang peraturan dan mengusulkan perbaikan melalui mekanisme yang ada</p>', ''),
(78, '<p>APBDes tidak transparan. Tindakan Anda&hellip;</p>', 'D', '4', '<p>Menunggu hasil pemeriksaan/audit sebagai dasar tindak lanjut</p>', '<p>Menyampaikan informasi secara terbatas di internal sambil menyiapkan klarifikasi</p>', '<p>Mengkoordinasikan pelaporan kepada pihak berwenang untuk dilakukan pembinaan dan evaluasi</p>', '<p>Menginisiasi keterbukaan informasi kepada masyarakat sesuai ketentuan yang berlaku</p>', ''),
(79, '<p>Kepala desa dominan dalam pengambilan keputusan tanpa musyawarah. Anda&hellip;</p>', 'C', '4', '<p>Mengikuti keputusan yang ada sambil menyesuaikan pelaksanaan agar tetap berjalan baik</p>', '<p>Mengkomunikasikan kepada pihak terkait untuk evaluasi mekanisme pengambilan keputusan</p>', '<p>Mengingatkan secara konstruktif pentingnya musyawarah dalam pengambilan keputusan</p>', '<p>Menyampaikan pandangan secara terbatas dalam forum yang tersedia</p>', ''),
(80, '<p>Program tidak sesuai kebutuhan warga. Anda&hellip;</p>', 'A', '4', '<p>Menginisiasi evaluasi melalui musyawarah desa untuk penyesuaian program</p>', '<p>Melakukan evaluasi internal terlebih dahulu sebelum dibahas dalam forum yang lebih luas</p>', '<p>Menjalankan program sambil melakukan penyesuaian terbatas di lapangan</p>', '<p>Melanjutkan program sesuai rencana sambil menunggu arahan lebih lanjut</p>', ''),
(81, '<p>Dana desa salah penggunaan. Anda&hellip;</p>', 'C', '4', '<p>Mengkoordinasikan evaluasi penggunaan anggaran untuk perbaikan ke depan</p>', '<p>Menunggu hasil pemeriksaan sebagai dasar tindak lanjut</p>', '<p>Melakukan evaluasi dan melaporkan sesuai mekanisme yang berlaku</p>', '<p>Memberikan teguran sambil melakukan pemantauan</p>', ''),
(82, '<p>Musyawarah tidak melibatkan warga. Dampak utama&hellip;</p>', 'A', '4', '<p>Berkurangnya kualitas keputusan karena minim partisipasi masyarakat</p>', '<p>Keputusan tetap berjalan namun kurang representatif</p>', '<p>Proses menjadi lebih cepat namun kurang aspiratif</p>', '<p>Proses tetap berjalan sesuai rencana awal</p>', ''),
(83, '<p>Kegiatan desa tidak terdokumentasi. Anda&hellip;</p>', 'A', '4', '<p>Menyusun dan memperbaiki sistem administrasi secara menyeluruh</p>', '<p>Menyusun sistem pencatatan dasar untuk kegiatan berjalan</p>', '<p>Mengingatkan petugas agar lebih tertib administrasi</p>', '<p>Menunggu laporan disusun secara bertahap</p>', ''),
(84, '<p>Warga protes pembangunan tidak merata. Anda&hellip;</p>', 'B', '4', '<p>Melakukan evaluasi internal terhadap distribusi pembangunan</p>', '<p>Melakukan evaluasi dan perencanaan ulang secara partisipatif</p>', '<p>Memberikan penjelasan kepada warga terkait kondisi yang ada</p>', '<p>Menyampaikan bahwa pembangunan berjalan sesuai rencana</p>', ''),
(85, '<p>Perangkat desa tidak disiplin. Anda&hellip;</p>', 'D', '4', '<p>Mengamati kondisi sebelum mengambil tindakan lebih lanjut</p>', '<p>Memberikan teguran untuk perbaikan sikap kerja</p>', '<p>Memberikan pembinaan dan pengawasan secara berkala</p>', '<p>Membina dan melakukan evaluasi kinerja secara berkelanjutan</p>', ''),
(101, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga mengeluh pelayanan lambat. Anda&hellip;</span></span></p>', 'A', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan antrean sambil mempercepat proses sesuai SOP</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan kondisi antrean dan alur pelayanan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Meminta warga menunggu sesuai giliran</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke petugas lain yang tersedia</span></span></p>', ''),
(102, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga tidak memahami prosedur surat. Anda&hellip;</span></span></p>', 'B', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberikan penjelasan singkat sesuai alur</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan rinci dan memastikan warga memahami</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke papan informasi pelayanan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke petugas lain untuk penjelasan</span></span></p>', ''),
(103, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Terjadi kesalahan data oleh petugas. Anda&hellip;</span></span></p>', 'C', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memperbaiki tanpa konfirmasi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memperbaiki sambil memberi catatan internal</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengakui dan memperbaiki sesuai prosedur</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menunggu konfirmasi sebelum memperbaiki</span></span></p>', ''),
(104, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga minta dipercepat tanpa alasan. Anda&hellip;</span></span></p>', 'D', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke petugas lain</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberi prioritas terbatas jika memungkinkan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menolak sesuai aturan secara tegas</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan prosedur secara sopan</span></span></p>', ''),
(105, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Antrean panjang di kantor desa. Anda&hellip;</span></span></p>', 'A', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menambah loket/petugas pelayanan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengatur alur antrean lebih efisien</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan kondisi kepada warga</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membatasi jumlah pelayanan sementara</span></span></p>', ''),
(106, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga marah karena layanan lama. Anda&hellip;</span></span></p>', 'A', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menenangkan dan mencari solusi pelayanan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan kondisi sambil tetap melayani</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke petugas lain</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjaga jarak agar situasi kondusif</span></span></p>', ''),
(107, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Perbedaan informasi antar petugas. Anda&hellip;</span></span></p>', 'B', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengkoordinasikan penyamaan persepsi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyamakan informasi sesuai SOP</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengikuti informasi yang paling umum digunakan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyampaikan ke atasan untuk klarifikasi</span></span></p>', ''),
(108, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga tidak paham pelayanan digital. Anda&hellip;</span></span></p>', 'C', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke petugas lain</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan cara penggunaan sistem</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberikan pendampingan langsung</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke panduan digital</span></span></p>', ''),
(109, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Data warga tidak sesuai. Anda&hellip;</span></span></p>', 'B', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Melakukan pengecekan ulang data</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Verifikasi dan perbaiki sesuai dokumen</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menggunakan data yang paling mendekati</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan warga melengkapi data</span></span></p>', ''),
(110, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Permintaan informasi sensitif. Anda&hellip;</span></span></p>', 'C', '5', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke pejabat berwenang</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberikan sebagian informasi yang diperbolehkan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan batasan sesuai aturan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menolak secara umum tanpa detail</span></span></p>', ''),
(111, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Pelayanan tidak sesuai SOP. Anda&hellip;</span></span></p>', 'D', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyesuaikan secara bertahap ke SOP</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Melaporkan untuk evaluasi </span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membiarkan sambil mengamati</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengembalikan ke SOP yang berlaku</span></span></p>', ''),
(112, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga tidak puas. Anda&hellip;</span></span></p>', 'C', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan kembali prosedur</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menampung keluhan untuk evaluasi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mendengarkan dan memperbaiki layanan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyampaikan alasan pelayanan</span></span></p>', ''),
(113, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Keluhan berulang. Anda&hellip;</span></span></p>', 'D', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Melaporkan kondisi ke pimpinan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menangani keluhan satu per satu </span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menganalisis penyebab utama</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Evaluasi sistem pelayanan</span></span></p>', ''),
(114, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Warga lansia kesulitan. Anda&hellip;</span></span></p>', 'B', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberi prioritas pelayanan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberi bantuan khusus sesuai kebutuhan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan secara lebih perlahan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke keluarga pendamping</span></span></p>', ''),
(115, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Petugas tidak disiplin. Anda&hellip;</span></span></p>', 'A', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membina dan melaporkan jika berulang</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberi teguran dan pengawasan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengingatkan secara informal</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyampaikan ke atasan</span></span></p>', ''),
(116, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Waktu pelayanan terbatas. Anda&hellip;</span></span></p>', 'C', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menambah waktu jika memungkinkan </span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengatur prioritas pelayanan </span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengatur waktu secara efisien</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membatasi jenis layanan</span></span></p>', ''),
(117, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Konflik antar warga. Anda&hellip;</span></span></p>', 'C', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menenangkan situasi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke pihak berwenang</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjadi penengah netral</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menghindari konflik langsung</span></span></p>', ''),
(118, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Sistem lama menghambat. Anda&hellip;</span></span></p>', 'D', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengevaluasi sistem berjalan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjalankan sesuai kondisi </span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Melaporkan kendala sistem</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengusulkan perbaikan sistem</span></span></p>', ''),
(119, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Permintaan di luar jam kerja. Anda&hellip;</span></span></p>', 'A', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Membantu jika memungkinkan sesuai aturan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyarankan datang saat jam kerja</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memberi solusi alternatif</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menolak secara sopan</span></span></p>', ''),
(120, '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Informasi pelayanan tidak jelas. Anda&hellip;</span></span></p>', 'D', '6', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Mengarahkan ke papan informasi</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menjelaskan saat diminta</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Menyediakan informasi tambahan</span></span></p>', '<p><span style=\"font-size:11.0pt\"><span style=\"font-family:&quot;Calibri&quot;,sans-serif\">Memperjelas melalui media &amp; petugas</span></span></p>', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `soaltpa`
--
ALTER TABLE `soaltpa`
  ADD PRIMARY KEY (`id_soal`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `soaltpa`
--
ALTER TABLE `soaltpa`
  MODIFY `id_soal` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=126;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
